server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS DESAFIO_XML
  application:
    name: ${name:desafio-xml}
  jpa:
    show-sql: true
  h2:
    console:
      settings:
        web:
          allow:
            others: true
      enabled: true
      path: /h2-console
security:
  oauth2:
    client:
      scope: password
      client-id: developer-challenge
      client-secret: developer-challenge

repo:
  url: https://github.com/adquizilla/developer-challenge.git
